Support details
FACG5/Qattan-foundation pull request #48
Opened 2018-10-07 10:40 UTC by AsalaKM

Technical support ticket details and allow the manager to update it

- [ ] View the details of ticket.
- [ ] Update ticket and add new status or action for it.

**Relates #12**

2018-10-07 13:27 UTC, FarahZaqout requested changes

2018-10-07 13:27 UTC, FarahZaqout commented on public/js/updateTicket.js
> +        console.log(response.res);
Remove console.log

2018-10-07 13:27 UTC, FarahZaqout commented on src/controllers/supportDetails.js
> +      console.log(err);
remove console.log

2018-10-07 13:27 UTC, FarahZaqout commented on src/model/queries/ticket.js
> +  console.log(sql);
remove console.log

2018-10-08 04:04 UTC, FarahZaqout requested changes
There's still a console.log

2018-10-08 07:23 UTC, FarahZaqout approved these changes

2018-10-08 07:28 UTC, SalwaMugh approved these changes

2018-10-08 07:37 UTC, merged