Reports page
FACG5/Qattan-foundation pull request #53
Opened 2018-10-08 13:15 UTC by AsalaKM

**Reports Page**
Allow the manager to view all report by status, type or period

> By Selected Period
> By Selected Status
> By Selected Type

**Relates #17**

2018-10-09 08:05 UTC, FarahZaqout requested changes
2 Comments, plus, all sql statements should be in uppercase letters.

2018-10-09 08:05 UTC, FarahZaqout commented on public/js/report.js
> +//   element.style.display = 'none';
No commented code.

2018-10-09 08:05 UTC, FarahZaqout commented on src/model/database/dbBuild.sql
> +    status VARCHAR UNIQUE
This change is not acceptable.

2018-10-10 08:41 UTC, SalwaMugh approved these changes

2018-10-10 23:26 UTC, FarahZaqout requested changes

2018-10-10 23:26 UTC, FarahZaqout commented on src/model/queries/ticket.js
> +const getAllTicket = () => {
This function is the same as the one below it. This will crash the server for sure.

2018-10-13 18:22 UTC, FarahZaqout requested changes

2018-10-13 18:22 UTC, FarahZaqout commented on src/controllers/reports.js
> +    const tLoans = await getLoans();
tLoans is not a good name.

2018-10-13 18:28 UTC, AsalaKM commented on src/controllers/reports.js
> +    const tLoans = await getLoans();
ok

2018-10-14 09:32 UTC, OnsNader approved these changes

2018-10-14 09:52 UTC, closed without merging