User experience
FACG5/Qattan-foundation pull request #54
Opened 2018-10-09 04:38 UTC by AsalaKM

**Edit User Experience**     **&**     **Add master style**
Adding a new Routs and links to make the user experience good in the site.
Adding master styles that we needed in the site

2018-10-09 07:32 UTC, FarahZaqout commented
1- pull requests should always relate to issues.
2 - I still don't understand what the pull request does exactly. User experience where? What was the problem or what did we solve?

2018-10-10 08:26 UTC, FarahZaqout commented
Resolve conflicts.

2018-10-10 08:42 UTC, SalwaMugh approved these changes

2018-10-10 10:46 UTC, FarahZaqout requested changes

2018-10-10 10:46 UTC, FarahZaqout commented on src/controllers/supportDetails.js
> +    .then(res.send(data))
this needs to be a callback.
inside the ```.then()``` will always fire if it's not inside a callback. Even if it's an error.

2018-10-10 10:46 UTC, FarahZaqout commented on src/model/queries/ticket.js
> +    text: 'SELECT COUNT(ticket_no) from ticket Where status_type NOT like $1',
capitalize sql statements.

2018-10-10 10:46 UTC, FarahZaqout commented on src/views/homeManager.hbs
> +            <a href="/closed/not">
```/closed/not/```
```/solved/solved``` do not make much sense

2018-10-10 13:19 UTC, FarahZaqout approved these changes

2018-10-10 13:19 UTC, merged