Employee home
FACG5/Qattan-foundation pull request #62
Opened 2018-10-10 12:20 UTC by AsalaKM

**Emplouee home**
> Add new rout for employee (/employee-home)
> View all ticket that's related to the logged employee
> #6"

2018-10-10 12:59 UTC, FarahZaqout requested changes

2018-10-10 12:59 UTC, FarahZaqout commented on public/js/employee.js
> +function move(x) {
x is not a readable name.

2018-10-10 12:59 UTC, FarahZaqout commented on src/controllers/employee.js
> +        if (x.status_type === 'solved') {
x is not a readable name

2018-10-10 13:09 UTC, OnsNader commented on public/js/employee.js
> +function move(x) {
noted

2018-10-10 13:10 UTC, OnsNader approved these changes

2018-10-11 10:03 UTC, FarahZaqout requested changes
Login with employee credentials returns error 404

2018-10-11 10:27 UTC, FarahZaqout requested changes

2018-10-11 10:27 UTC, FarahZaqout commented on src/views/employee.hbs
> +        <h2 class="greet">أهلا في مركز القطان للدعم الفني </h2>
Qattan center is not a tech support center.

Should say something like: "tech support department of al qattan"

2018-10-11 10:41 UTC, FarahZaqout approved these changes

2018-10-11 10:42 UTC, merged