Add Ticket
FACG5/Qattan-foundation pull request #63
Opened 2018-10-10 13:08 UTC by AsalaKM

**Add Ticket page**
 Allow the logged employee to add new ticket In both of type (support or loan)
**#7**

2018-10-10 13:25 UTC, OnsNader approved these changes

2018-10-10 14:06 UTC, FarahZaqout commented
This is still work in progress. PR name should reflect that.
@OnsNader Don't just approve for the sake of approval. The file has conflicts with master.

2018-10-11 14:09 UTC, SalwaMugh approved these changes

2018-10-13 02:22 UTC, FarahZaqout requested changes

2018-10-13 02:22 UTC, FarahZaqout commented on public/js/addTicket.js
> +const empDep = 'information technology';
This was done for testing purposes. It should be replaced with the actual field value.

2018-10-13 02:22 UTC, FarahZaqout commented on public/js/addTicket.js
> +    const empC = empName;
empC, depC...etc is not descriptive.

2018-10-13 02:22 UTC, FarahZaqout commented on public/js/addTicket.js
> +const pType = document.querySelector('#ptype-support');
use descriptive names please.

2018-10-13 11:20 UTC, FarahZaqout approved these changes

2018-10-13 11:21 UTC, merged